### ISSUE TITLE
[error] Check failed: ExactNumBottomBlobs() == bottom.size() (2 vs. 3) TripletLoss Layer takes 2 bottom blob(s) as input.

### ISSUE THREAD

**Issue by peternara** [tyandzx/caffe#6]
hi.
i try your triplet loss. but i have next problem.

F0721 12:28:31.108945 19808 layer.hpp:374] Check failed: ExactNumBottomBlobs() == bottom.size() (2 vs. 3) TripletLoss Layer takes 2 bottom blob(s) as input.
*** Check failure stack trace: ***
    @     0x7fa8885d0b5d  google::LogMessage::Fail()
    @     0x7fa8885d4b77  google::LogMessage::SendToLog()
    @     0x7fa8885d29f9  google::LogMessage::Flush()
    @     0x7fa8885d2cfd  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fa88e3e1f01  caffe::Layer<>::CheckBlobCounts()
    @     0x7fa88e42de13  caffe::Net<>::Init()
    @     0x7fa88e43028b  caffe::Net<>::Net()
    @     0x7fa88e50778a  caffe::Solver<>::InitTrainNet()
    @     0x7fa88e507e74  caffe::Solver<>::Init()
    @     0x7fa88e5083a8  caffe::Solver<>::Solver()
    @     0x7fa88e409d13  caffe::Creator_SGDSolver<>()
    @           0x412193  caffe::SolverRegistry<>::CreateSolver()
    @           0x40c0c8  train()
    @           0x4089af  main
    @       0x33f3a1ed5d  (unknown)
    @           0x407ef9  (unknown)
중지됨

Is triplet loss  need  3 input size ?

**Comment by tyandzx** [comment]
Actually, triplet loss layer need 2 input from bottom, seems you have given it 3.

**Comment by peternara** [comment]
thank you~!!

**Comment by Awadhesh42** [comment]
how to give inputs from bottom in caffe??

**Comment by Awadhesh42** [comment]
F0411 20:43:48.466460  4484 layer.hpp:349] Check failed: ExactNumBottomBlobs() == bottom.size() (2 vs. 3) SoftmaxWithLoss Layer takes 2 bottom blob(s) as input.
*** Check failure stack trace: ***
./experiments/scripts/wpal_net.sh: line 39:  4484 Aborted                 (core dumped) ./tools/train_net.py --gpu ${GPU_ID} --solver models/${NET}/solver.prototxt --weights ${WEIGHTS} --db ${DB} --setid ${DB_SET} --outputdir data/snapshots/${NET}/${DB_SET} --iters ${ITERS} ${EXTRA_ARGS}

**Comment by adityag6994** [comment]
@peternara please tell your work around.

Best,
Aditya
